package hibernate;
// Generated 27/10/2019 12:42:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Riegos generated by hbm2java
 */
public class Riegos  implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "id")
     private int id;
     private Date fecha;
     private Integer productosId;

    public Riegos() {
    }

    @Override
    public String toString() {
        return "Riegos{" + "id=" + id + ", fecha=" + fecha + ", productosId=" + productosId + '}'+"\n";
    }

	
    public Riegos(int id) {
        this.id = id;
    }
    public Riegos(Date fecha, Integer productosId) {
       this.fecha = fecha;
       this.productosId = productosId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getProductosId() {
        return this.productosId;
    }
    
    public void setProductosId(Integer productosId) {
        this.productosId = productosId;
    }




}


