package hibernate;
// Generated 27/10/2019 12:42:01 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;




/**
 * Tipoproducto generated by hbm2java
 */
public class Tipoproducto  implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name = "id")
     private Integer id;
     private Integer idTipoProducto;
     private String nombreTipo;
     private String descripcion;
     private Integer productosId;

    public Tipoproducto() {
    }

    public Tipoproducto(Integer idTipoProducto, String nombreTipo, String descripcion, Integer productosId) {
       this.idTipoProducto = idTipoProducto;
       this.nombreTipo = nombreTipo;
       this.descripcion = descripcion;
       this.productosId = productosId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getIdTipoProducto() {
        return this.idTipoProducto;
    }
    
    public void setIdTipoProducto(Integer idTipoProducto) {
        this.idTipoProducto = idTipoProducto;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getProductosId() {
        return this.productosId;
    }
    
    public void setProductosId(Integer productosId) {
        this.productosId = productosId;
    }

    @Override
    public String toString() {
        return "Tipoproducto{" + "id=" + id + ", nombreTipo=" + nombreTipo + ", descripcion=" + descripcion + '}';
    }




}


